// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8dgD0Irc6WTCzH70bzIrGWQx1rGdNuzE',
    appId: '1:498159267515:web:f2ac190cf642f2de31439e',
    messagingSenderId: '498159267515',
    projectId: 'tiktwin-flutter',
    authDomain: 'tiktwin-flutter.firebaseapp.com',
    storageBucket: 'tiktwin-flutter.appspot.com',
    measurementId: 'G-ZLQTLW5QCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKoax-sAuD1bIHvLR3CSzYuwy9AJcbHyk',
    appId: '1:498159267515:android:9652495b5ec85cea31439e',
    messagingSenderId: '498159267515',
    projectId: 'tiktwin-flutter',
    storageBucket: 'tiktwin-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlgVuvMKDNxJa3v5X690E-gy0aKf_tbzo',
    appId: '1:498159267515:ios:df962d6b572c6b6631439e',
    messagingSenderId: '498159267515',
    projectId: 'tiktwin-flutter',
    storageBucket: 'tiktwin-flutter.appspot.com',
    iosBundleId: 'com.example.tiktwinFlutter',
  );
}
